from scrapers.base_scraper import BaseScraper
from scrapers.lv_zva import LvZvaScraper
from scrapers.es_aemps import EsAempsScraper
from scrapers.it_aifa import ItAifaScraper
from scrapers.de_bfarm import DeBfarmScraper
from scrapers.fr_ansm import FrAnsmScraper
from scrapers.no_dmp import NoDmpScraper
from scrapers.cz_sukl import CzSuklScraper
from scrapers.eu_ema import EuEmaScraper
from scrapers.se_lv import SeLvScraper
from scrapers.dk_lmst import DkLmstScraper
from scrapers.fi_fimea import FiFimeaScraper
from scrapers.be_famhp import BeFamhpScraper
from scrapers.ie_hpra import IeHpraScraper
from scrapers.is_lyfja import IsLyfjaScraper
from scrapers.gr_eof import GrEofScraper
from scrapers.hr_halmed import HrHalmedScraper
from scrapers.ro_anm import RoAnmScraper
from scrapers.sk_sukl import SkSuklScraper
from scrapers.nl_igj import NlIgjScraper
from scrapers.at_basg import AtBasgScraper
from scrapers.pt_infarmed import PtInfarmedScraper
from scrapers.us_fda import UsFdaScraper
from scrapers.ca_hpsc import CaHpscScraper
from scrapers.au_tga import AuTgaScraper
from scrapers.ch_drugshortage import ChDrugShortageScraper
from scrapers.kr_mfds import KrMfdsScraper
from scrapers.tr_titck import TrTitckScraper
from scrapers.my_npra import MyNpraScraper
from scrapers.cl_isp import ClIspScraper
from scrapers.br_anvisa import BrAnvisaScraper
from scrapers.co_invima import CoInvimaScraper
from scrapers.hu_ogyei import HuOgyeiScraper
from scrapers.ee_ravimiamet import EeRavimiametScraper
from scrapers.si_cbz import SiCbzScraper
from scrapers.lt_vvkt import LtVvktScraper
from scrapers.sa_sfda import SaSfdaScraper
from scrapers.pk_drap import PkDrapScraper
from scrapers.ph_fda import PhFdaScraper
from scrapers.in_cdsco import InCdscoScraper
from scrapers.sg_hsa import SgHsaScraper
from scrapers.il_moh import IlMohScraper
from scrapers.ar_anmat import ArAnmatScraper
from scrapers.pe_digemid import PeDigemidScraper
from scrapers.mx_cofepris import MxCofeprisScraper
from scrapers.tw_tfda import TwTfdaScraper
from scrapers.eg_eda import EgEdaScraper
from scrapers.za_sahpra import ZaSahpraScraper
